services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: thala-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-thala}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-YbgdwCSWmX7qtM6cXqAi}
      POSTGRES_DB: ${POSTGRES_DB:-thala}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-thala}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - thala-network

  # FastAPI Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thala-backend
    restart: unless-stopped
    environment:
      # Database
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-thala}:${POSTGRES_PASSWORD:-YbgdwCSWmX7qtM6cXqAi}@db:5432/${POSTGRES_DB:-thala}

      # Authentication
      JWT_SECRET: ${JWT_SECRET:-99d224e68e4abbd160bd52d52ba06590551668fe534128c605a66c3295a3ae40}
      GOOGLE_OAUTH_CLIENT_ID: ${GOOGLE_OAUTH_CLIENT_ID}

      # CORS
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-https://thala.app,https://www.thala.app,http://localhost:3000,http://localhost:8080}

      # Rate Limiting
      RATE_LIMIT_ENABLED: ${RATE_LIMIT_ENABLED:-true}
      RATE_LIMIT_REQUESTS_PER_MINUTE: ${RATE_LIMIT_REQUESTS_PER_MINUTE:-60}
      RATE_LIMIT_BURST: ${RATE_LIMIT_BURST:-10}

      # App Settings
      APP_NAME: ${APP_NAME:-Thala Backend}
      API_V1_PREFIX: ${API_V1_PREFIX:-/api/v1}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: 3
    networks:
      - thala-network

volumes:
  postgres_data:
    driver: local

networks:
  thala-network:
    driver: bridge
